version: '3.8'

services:
  frontend:
    image: ashoksanareddy/doxie_fe
    container_name: fe
    ports:
      - "5173:5173"

  backend:
    image: ashoksanareddy/doxie_fe
    container_name: be
    ports:
      - "5001:5000"
    environment:
      MONGO_URI: mongodb://database:27017

  database:
    image: jp0411/database:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
